GH1 - xts allocator server
rdkcentral/xts_allocator_server pull request #3
Opened 2024-11-28 09:03 UTC by zghp

2024-12-05 14:18 UTC, zghp commented on logo.png
I optimised the image. It's generated using ai

2024-12-05 15:35 UTC, mhughesacn commented on logo.png
The size is fine now - thank you.  But I'm not sure about the origin.  Do you have a permission for AI-generated imagery that I could refer to?

2024-12-06 16:18 UTC, TB-1993 requested changes
This looks great, just need to fill out the requirements.txt. The next step is writing a build script to build it into a single binary. But we'll do that as the next ticket.

2024-12-06 16:18 UTC, TB-1993 commented on templates/index.html
> +        <a href="/list_slots">View Slots</a>
This is a very neat idea, nicely done 😄

2024-12-12 12:43 UTC, TB-1993 approved these changes
Looks good, ship it. Can you please raise another ticket on this repo to create an installation and build script? That will integrate it with pyinstaller for building it as a single binary for people to run.

2024-12-13 09:38 UTC, merged