gh4 - build script
rdkcentral/xts_allocator_server pull request #5
Opened 2024-12-16 09:49 UTC by zghp

2024-12-16 09:50 UTC, zghp commented on build_script.py
> +        "--noconsole",             # hides the console (optional?)
should i keep the noconsole param?

2024-12-16 10:30 UTC, TB-1993 requested changes

2024-12-16 10:30 UTC, TB-1993 commented on build_script.py
> +    subprocess.check_call(pyinstaller_cmd)
Any reason you're not using subprocess.run here?

2024-12-16 10:30 UTC, TB-1993 commented on build_script.py
I'm not sure doing this as a python file is the best idea, since it's all just running subprocess for everything anyway. If we do it in a shell script you can set up a python venv too, with all the requirements installed. Then run all the commands.

2024-12-19 17:39 UTC, TB-1993 approved these changes
Looks good, ship it!

2024-12-20 14:38 UTC, merged